name: conformance with Prettier

on:
  push:
    paths: ['src/**.ts', '.prettierrc.json']
  pull_request:
    paths: ['src/**.ts', '.prettierrc.json']

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install # npm ci
      - name: Run prettier
        run: npm run style:check
